kind: pipeline
type: docker
name: trigger

steps:
  - name: fetch-gomstore-repo
    image: golang:1.17-alpine
    commands:
      - apk add --update git gcc
      - git clone -b drone https://github.com/murat/gomstore.git && cd gomstore
      - go mod download
      - go test ./... -coverprofile=coverage.out && go tool cover -html=coverage.out -o coverage.html
