kind: pipeline
type: docker
name: trigger

steps:
  - name: trigger-gomstore-tests
    image: plugins/webhook
    settings:
      urls: https://cloud.drone.io/api/repos/murat/gomstore/builds?branch=drone
      token_type: Bearer
      token_value:
        from_secret: DRONE_TOKEN
